<?php
class Tscopes extends MpiController {
  var $skip_before_action = "*";
  var $display_value;

  function init(){
    parent::init();
    $scope = Scope::find(2);
  }

  function has_searchable_access(){
    $scope = Scope::find(2);
    $params = array(
      "p_fingerprint_r3"=>"",
      "p_fingerprint_l5"=>"",
      "p_fingerprint_l1"=>"",
      "p_fingerprint_l2"=>"p/8BHrkAtgABVQCsALsAAU8AwgDBAAFVAKIAtwABTwDOAKoAAVoAkwANAQH+AMQATwABpACzANoAAgMBqQD2AAFPAOEAxgABWgDRAPcAAVUApQBlAAHAAMIAggABdwCOAOkAAf4AgwAeAQE+AJgAIwEC8gCNAN0AAUoAywAXAQEDAcUA/AABAwG6AAYBAU8AuwBhAAFYAdUAfgABggCGADMBAecA1gBJAAGeAKAAmgABSgCfAJEAATkAYQBzAALnALUAbgACpABxABYBAfIAZQDmAAFKAKIAGBkBAw0QEgoCABsUAQATEhsLBhcMFQ4cFAYWDg8OCxQDAA4FAgEPBRMIAAQWDxETDBsCBBMKERIDGAcCEggIBwgNCQIFCAcBEQoJBAwUAgMbBhwFARgUFwcAFhwVGwUNEAcZDAEEAxkLBhIHCBAAGBUUBwMNBwoIFgUFEwwLDR0ZGw8cHRAKBxgMBAwQAwkAGQsBGRMHABkEFQ8TEAEDBBEIBRAPCBgbHB0EGBUGGxcHCQwGDxEKCQIYBBkVFxgLBRIADBMNDQMJARwNFQsODQ0BBwQOCAoCCxcZFBkVEQUSDRICEAAPDQUHDBcQAg8SDhMFHRIJGBQcEBwIDh0EGwkDBQoRBxYTGRoaCxYIEBgCFQgdDhEJFRYNGBoWEQkMGQYdAx0HHQEYBhobEQkZFxoUAxodGAQXDBoBGhoGCRQdGgkX",
      "p_fingerprint_r1"=>"",
      "p_fingerprint_l4"=>"",
      "p_fingerprint_r4"=>"",
      "p_pat_gender"=>"1",
      "p_fingerprint_r2"=>"p/8BHpMADQEBJQHIAK8AATYBygDtAAErAdUAvwABggCDAMAAAWsA4wCeAAGHAKwAWAABngB4AMIAAWYA1wDWAAF8AGsAwAABWgCbAEsAAV0BwwAvAQI2AbQA/QACKwGZANQAAXcAfAAfAQElAaIA7QABKwGnALIAAXwArgDrAAF3AJsAfQABpACQAOQAASUBtgDhAAF3ALMANAABpADlANkAATABpwAYAAFYAcMAOAECRwHfAC4BATYBmQDpAAJxAOgAXgABRwGSAKkAAYIAbgD6AAFxAK0AGAsPGhoTBwQPEREUBwkWCBMNDBEPExoNBgoDAREaCAMPFBAcAhQECQwPAggMAg8NBBwLGQwUAhEOAA0EGBkVFxoUFgMRExENAQUUDRABChUMGgIWFAgADwAaAwUHHAAMDRAGFQ0HEwQTFAQQAg8dEw4dEgYAEwgBEwcAHQARDBMNHAkcHBIRCB0aFAMCAxoEFBYDEAwNFBACGhIKBxANCRoHFgEMCBMJChcLDBQBEBIBHB0PAg0TEA8EABQREAgFHQ0ADR0HERYdCREDCwAWBRMcDQEbBg4aFAQYDAwWGgkJEA4THQQQBQ4PGAAGFwUbGQwLAg4MARIZAhsVCxEEEg4RCw4LDxgCGA4SFQcSGwoFEhgRAAcUBQkSGA8ZABIbGREcBhkWGRQBGxkIAxIFBh0cEAYcChsXAxsZDhIXFBIQCgEKBRUWEhwVFhsBFQkKHBcFFxAXCRUJFw==",
      "p_pat_register_site"=>"0202",
      "p_fingerprint_l3"=>"",
      "p_fingerprint_r5"=>"",
      "visits" => "virtual_field");
    $result = $scope->has_searchable_access($params);
    ILog::d("result: ", $result);
  }
}
