<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed'); ?>

INFO  - 2017-01-26 04:48:27 --> Create Visit
INFO  - 2017-01-26 04:48:28 --> Array
(
    [patientid] => KH002100003318
    [age] => 30
    [serviceid] => 2
    [visitdate] => 2017/01/20
    [externalcode] => 343434
    [externalcode2] => 
    [info] => Initial Visit
    [vcctsite] => 
    [vcctnumber] => 
    [refer_to_vcct] => 0
    [refer_to_oiart] => 0
    [refer_to_std] => 0
    [sitecode] => 0206
    [member_fp_name] => member_fp_r2
    [member_fp_value] => p/8BHogABgECOwGhAGkAAYIAYACqAAFxAJoAqAABdwBpAMMAASsBPwCZAAFmAHkArgABdwCMAL0AASsBlwCNAAF8AGoAfwABggCkAKkAASsBWwDmAAErAWUAIwABpABXAEsAAbQAMwBYAAEoAJ8AJwABQQGJAHoAATYBtQD2AAE2AVQAGQABYwFKAJQAAXEAogAFAQFBAVEAeQABZgBWAHoAAYcArAAeAQFMAbgAIgEBngAxADYAARcAvwAfAQFSAbsALQEBWAG1ADEBAaQASAB3AAHcAKYAFhUcGxgaFR0KAxsYBRMYFxYdHBgbGhoXDBIcFwkWHBobFwcGFBEIEAYCBwMEBgkVABQEAgMIFxQTFRMWEAETHQITBwoKCAkQDhkGAwkdBR0EBxgUBRUdDgIFCAELBA4NEwkFFhoUFxENDBoRBgoXAA0ZGBECCRUOBggZEh0NFQ0WDRsUCAkHAgARHBQWDgcIAhYGCQMQDRIFCRAWAhUGEwoQBhAJDRkMGxEACwQTGAAEAwIdEBUCAw8MBAUJARwRCwIaAAYFAggcAAMJAwEKAQQKCwcLBhMOGwAFDgEPCQ4HEAQJAgodGRANEQcOEg4MAAcVGQAEEw0UBw8SFAsWGRYBEQoGAQENDQ8FDQsFEQMLExAPBwEVDBYMHQwIDRQKCRkdEhUSFhIXCwgPFwcJDxEIGgcYBxYPHAsbCxoKHAcRARcBGgERDxoNGg8=
)

INFO  - 2017-01-26 04:56:29 --> Synchronization Update
INFO  - 2017-01-26 04:56:29 --> Array
(
    [patient] => {"patientid":"2178e8ab-dc63-444d-bbc7-ce518a93ae25","fingerprint_r1":"","fingerprint_r2":"p/8BHWIAxgABYABJALcAAVUA3ACOAAF8AKkAsgABcQBuAOMAAR8BUQDfAAFgAHwALAEBRwFyAOsAAXEAcwAIAQE7AY0AdAABtABxAHwAATMAqAAxAAFMAaEAJgEBNgFfAIMAAUQAZAB7AAHyAKMAXQABTAF1AHMAAeEAbgBkAAEtAMsAIwEBggCqADMBAYIAxgAoAQE2AVkANgEBggC4AAwBATYBgwCWAAFPAF8AGgEBhwCSAJkAAXcAkQA4AQE7AdoAMgABhwCBACUAAQAAowAUEg0OBwQKEAoOGRcTDBARDhANCgkQChEaDBoGDhEaEw0QGAgIBwQFCgkAARUYExQFABIWBAAUFhcKCQ8GGA0RAxkMFgkRFwkHBRUGExIGDAYIGQkIBBQMFxAHABMWFw0LHAUBFw4OCQwSDwsZChMGAxcZEA0JGwsYBxAPFQgRDwgFFxEaFAwIGQ4ZDQENGhUYBBoIBAEAFxoYCg8aFhgFAwIZDxoSGREXDwYHBwEAGQEOERwPHAANARcMGAMJBhYIABYIDxsTCAEKCQsAAwYUBgQVDBkCDAcCDxELBAMWBw0PAwoQHBUHARkTGAcDBhIJHBUTBBkQCwIJAw8VBBUFChwGBRQIFwIbHBYDAREOHBIIAhsKCwUDDRwOCwkbGAEIAxQHEgcCEAILFQAWBRccEgMRGxAbFhkZGxUBFgIHAhICARwUAg==","fingerprint_r3":"","fingerprint_r4":"","fingerprint_r5":"","fingerprint_l1":"","fingerprint_l2":"p/8BHswAAAEBSgDTANkAAVUAuQAFAQFEAOUA1gACWgC5APsAAfgAqgDjAAHyAMMA7AABSgDgAN4AAlUA1QArAQJEANcAFAEBAwHZAOgAAgMBsQDOAAJKALoA1wACSgC7ALwAAWAAnAC+AAE5AJEAtwAB7QCAAPkAAe0AbgAXAQHnAHgALAEB5wBgABABATkAagABAQHtAIQACAEBOQDPADwBAfgAjQATAQE5APQAhgABggC0ALMAATkAGgA3AQF3AEoAPwEBpACXAIcAAdYAsQB7AAG6ALQABwMCBA0ZCgcODwwLFxUHARETFRAKARMUAQMWCAQGAAQFDAIACw0GCgoDAAYRFAULEhEICQYMCQAUEAYBAQwLDg4ZCxkACgYFDA0RFQIGFRQEBRwdFxARFw4NBgcSFwkCBgsPGREQCgwEDAELDBkSEwIFExUEChIVAQ0TEAkEFxQHDAwOCw8ABwUOAAEGAxYJDQ8FAQQBAgoFDQwDCAAJCgAFEhQXEwkGFwICDAgCEAUPHBsaARkEBwMNBg0FGQADFwQbEgcNBwsFDxsTDA8SEBUCFQUZHAMLGxEJBxUEDhwZHQgEFwUEEBYCCQEDGRYABg4JAw0cAgMQCxAODR0XAAgGCAoYHRAPDx0VBhYEGxQOHRQFCxwSAggXEQIVDhkYFhcNGBEEGxUaExsXAxgWBhUPCx0UDhQPFgoIAwwcEBkWEhsQARgaEQcYDB0cGBoSGhQLGBYRFBkaFRoQGhcUHBsWExwaDxoc","fingerprint_l3":"","fingerprint_l4":"","fingerprint_l5":"","gender":1,"age":null,"sitecode":"","datebirth":"","createdate":"2017-01-25 15:21:43","updatedate":"2017-01-25 15:21:43","visits":[]}
    [patientid] => KH015100000003
    [sitecode] => 0206
    [member_fp_name] => member_fp_r2
    [member_fp_value] => p/8BHogABgECOwGhAGkAAYIAYACqAAFxAJoAqAABdwBpAMMAASsBPwCZAAFmAHkArgABdwCMAL0AASsBlwCNAAF8AGoAfwABggCkAKkAASsBWwDmAAErAWUAIwABpABXAEsAAbQAMwBYAAEoAJ8AJwABQQGJAHoAATYBtQD2AAE2AVQAGQABYwFKAJQAAXEAogAFAQFBAVEAeQABZgBWAHoAAYcArAAeAQFMAbgAIgEBngAxADYAARcAvwAfAQFSAbsALQEBWAG1ADEBAaQASAB3AAHcAKYAFhUcGxgaFR0KAxsYBRMYFxYdHBgbGhoXDBIcFwkWHBobFwcGFBEIEAYCBwMEBgkVABQEAgMIFxQTFRMWEAETHQITBwoKCAkQDhkGAwkdBR0EBxgUBRUdDgIFCAELBA4NEwkFFhoUFxENDBoRBgoXAA0ZGBECCRUOBggZEh0NFQ0WDRsUCAkHAgARHBQWDgcIAhYGCQMQDRIFCRAWAhUGEwoQBhAJDRkMGxEACwQTGAAEAwIdEBUCAw8MBAUJARwRCwIaAAYFAggcAAMJAwEKAQQKCwcLBhMOGwAFDgEPCQ4HEAQJAgodGRANEQcOEg4MAAcVGQAEEw0UBw8SFAsWGRYBEQoGAQENDQ8FDQsFEQMLExAPBwEVDBYMHQwIDRQKCRkdEhUSFhIXCwgPFwcJDxEIGgcYBxYPHAsbCxoKHAcRARcBGgERDxoNGg8=
)

