<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed'); ?>

INFO  - 2017-01-19 05:18:28 --> Patient searching
INFO  - 2017-01-19 05:18:28 --> Array
(
    [fingerprint_r1] => 
    [fingerprint_r2] => p/8BHr8AjwABkwA3ABgBAU8AnADYAAJBAcUAwQABjQDXALYAAo0AwQDMAAJBAakAIwECawC7AOsAAYcALAAXAQL4ANQAoAABRwE8AOgAARcAvQAmAQFxAKYABgEBfADnAPkAAYIAmADFAAGTACgAFwEB+ABeAHoAAV0BGwD8AAEzAFMAngABYwE3AK0AAQwAGAC0AAHFACcAygABFwAmAGcAAbQAlAAOAQIlAX0AJwECUgHuAM8AAUEBfwAeAQFBAagAVAABTAHqAGcAAUEBVgAeAQGkAJoADwgYGgEIBQMBDwIOCwYXDAMEBAkaFwkAFRQGDA8RBhcFBAcFExIIERQTHQEVExgXGQQMBwMJBwIKFRIQCwwCBREKAREYHRodBQ4GGg0ZGQMdCAcDGAYZBQ4DDQcEABoMDAIdDwIDAQoLFwUJAwAIChEVDwoXBwcOGAwZCRcCBxkQFg0FCwcGBwoTABwHBB0KCRwFAAsNFRIAGwoUFBILGhgLHRcMBRMQDgQNAwwNDA4OAB0RAgQNBBwbDgkSFhoBExYRFBgBBg0GAhoCDxUKEggVFBYHCQ4SGQABFQQcAhkGHRgIGggQGxETCwIYDxoKGg8ZDgkbFBAYCgISDhAXChUQCgIDHAoOABAVFgsZDxQOExkcEgAFHAQbDAoDGxIbDhsKEAMQDhwWGwoWCgUQHA4WABY=
    [fingerprint_r3] => 
    [fingerprint_r4] => 
    [fingerprint_r5] => 
    [fingerprint_l1] => 
    [fingerprint_l2] => p/8BHqQAcQABhwC6AJoAAXEAmAB3AAE7AXoAWwABqQBtALsAAg4BkADLAAFPAE4AywABZgAtANsAAloAIwCaAAJKAHYAIAABAACYAB4AAVgBggApAAFdAYoAIwACpACWAP0AATkAnwAPAQHhAJ8ACAEBOQCYAAcBAe0AqAAdAQHcADUAFQEBOwGFAP0AASgAxwDIAAFmAMIA/wABTwBWAC0AAcUAawDHAAIUAXQAwAACCQEkACkBAUEBMQAhAQGNAHIAgAABpABwAJ0AAWsAagCcAAJgAKsAHB0ODw8QGAQQDQsMFxgOEBcEGhICAA8NGRoLCQwKEQ4TDQ4NDAkQExEPCwoZEhEQDxMdGwYXHBsFGAQcBB0OEwkKFgkYHAYEDxUYHRENBwYFFxsDBQQOFRsCERUGGAIDFxwXHRAVFQ0WCwADAQARExQBAQINBRMFAwsbABYMBRQGHRUUHAIFHAYcAwwDFh0CEgcDCQQbExcFHRAFFRMTGA8FGBsFAQYIBxcHCAUGHAMDChYKHAANFxMEDgUaBx0IFxsNFB0ABwQVBRwBEwYPFAcYHAgBGxIGEBcZBxAUGAEEAgALHQEOFAQIAgsADBQYBhsIGxITBQIAChMUAgwRBRcIBx0bCxsWAgoYCAEDERQaExoGAAkCCRMHFAASFxsJGwwCFhINEhAAFhkGGwoNARoQCAMZExoNGhcaDh0WERIaEQgWGRAZFxkNEggBChkRGQgFChQK
    [fingerprint_l3] => 
    [fingerprint_l4] => 
    [fingerprint_l5] => 
    [gender] => 1
    [sitecode] => V02-04
    [member_fp_name] => 
    [member_fp_value] => 
)

ERROR - 2017-01-19 05:18:28 --> SDK is busy with other service
INFO  - 2017-01-19 05:33:59 --> Patient searching
INFO  - 2017-01-19 05:33:59 --> Array
(
    [fingerprint_r1] => 
    [fingerprint_r2] => p/8BHYwAagACUgFLAH4AAgYApwAWAQKCAFIAHwEC+ACaAHYAAZ4AvgCBAAJMAVcA1AACFwBkALgAAboAXAC5AAEGAEYA/gABMwCSAN4AAZgAlwDLAAFMAZMAsgABUgG7AGsAAUwBRgDXAAHWAL4A7wABhwCQAC8BAkEBpQAlAQI2AVEATgACrwDWAAIBAjsBaQA0AAGkADUANgEBAwHFALcAAY0ArwA8AQFBAZgAOAECUgFwADYBAnwA1wA+AQE7AeAAKgEBOwF+ACQAAVgBpAAIBxgQEQIOBgQACgsaGwUNFxgYERARCwwXERQcBggGBxMPGRAQAhcQBA0DCRIUFQMOCBgCBQQZAwkOFwIYGRoXGxMOBwoMAg8JBgcMDwoNAAESCxYWDAITFxsPCxYFCwcIDAUAGREaEQ8WGxEVCRkVAgoREwoHGwIKBhEPGhMMBAgBCwgaAhIcGhgHARcZGQIAFAoWEAMGCwASCggMBRsPAQAGDBkJFxMAHAkIDAAYGxoQAw4YAw8MAwYKDgkHExYTCgILFg0WBBAPAQQQGwEUDA0QCgQUDgsJChoPBBIRAwsFEwsHBA4MAwIEHAYBBwAMARAJDgEVEAMKCAANHBkKBxYXAxUOCwAYFQ0UAhYBHBoZCw0KBRMMFQYPBwcFBxIIEg0SDwUVEQUcBRQbFhcVFQoVCBMFBxQMHAIFEw0aFRsFFQEbBBsN
    [fingerprint_r3] => 
    [fingerprint_r4] => 
    [fingerprint_r5] => 
    [fingerprint_l1] => 
    [fingerprint_l2] => p/8BF2MAVQABLQCzAOMAAWMByAAlAQGCANEAowABWAGyAPcAAZ4AvgDaAAGpAHAAVgAB3ADLAAQBAo0APQDZAAHhALgAqwABrwDVAPoAAZMAogCcAAK6AGUA1wAB1gBRAI4AAdwAcwALAQLhAH8AeAAC0QDiAI8AAlIB6AC/AAJMASwAKwEB7QAvALUAAeEAMwB6AAHhACcALwEBMwD1ALsAAUwBfAAVEgYAAQUHChEWBAEDEAkDCQsHBAQFAgcKBBEDDRQPBgoFCBMIDAoBBwEWAwcFAgoPAAUJERADCxYQBRELDwkQDQ8CBBMNEQkODAEJBQMTFA0AFAAKERYJBRYNBgERDBMLEA4EBQsCAQoWFAYBAwELDggHEQ4BDA0CBRQPCQ8ECQEWCA0EERIOEQsBDAsNBAwFEBIIBxYVDgoJDAsLBgoDDgcWCxUIBQwCDgMPDAkLAAEQCBQMDw4KEw8SDBAPDBQCERUMEwAOEwkGAhYTBgsUCA8BCBITEwsOCwkAFRMDBhAGAQ0MABAAEgQQDRUEEgESAgIIFQEVAg==
    [fingerprint_l3] => 
    [fingerprint_l4] => 
    [fingerprint_l5] => 
    [gender] => 1
    [sitecode] => V02-04
    [member_fp_name] => 
    [member_fp_value] => 
)

ERROR - 2017-01-19 05:33:59 --> SDK is busy with other service
INFO  - 2017-01-19 05:34:07 --> Patient registration
INFO  - 2017-01-19 05:34:07 --> Array
(
    [fingerprint_r1] => 
    [fingerprint_r2] => p/8BHYwAagACUgFLAH4AAgYApwAWAQKCAFIAHwEC+ACaAHYAAZ4AvgCBAAJMAVcA1AACFwBkALgAAboAXAC5AAEGAEYA/gABMwCSAN4AAZgAlwDLAAFMAZMAsgABUgG7AGsAAUwBRgDXAAHWAL4A7wABhwCQAC8BAkEBpQAlAQI2AVEATgACrwDWAAIBAjsBaQA0AAGkADUANgEBAwHFALcAAY0ArwA8AQFBAZgAOAECUgFwADYBAnwA1wA+AQE7AeAAKgEBOwF+ACQAAVgBpAAIBxgQEQIOBgQACgsaGwUNFxgYERARCwwXERQcBggGBxMPGRAQAhcQBA0DCRIUFQMOCBgCBQQZAwkOFwIYGRoXGxMOBwoMAg8JBgcMDwoNAAESCxYWDAITFxsPCxYFCwcIDAUAGREaEQ8WGxEVCRkVAgoREwoHGwIKBhEPGhMMBAgBCwgaAhIcGhgHARcZGQIAFAoWEAMGCwASCggMBRsPAQAGDBkJFxMAHAkIDAAYGxoQAw4YAw8MAwYKDgkHExYTCgILFg0WBBAPAQQQGwEUDA0QCgQUDgsJChoPBBIRAwsFEwsHBA4MAwIEHAYBBwAMARAJDgEVEAMKCAANHBkKBxYXAxUOCwAYFQ0UAhYBHBoZCw0KBRMMFQYPBwcFBxIIEg0SDwUVEQUcBRQbFhcVFQoVCBMFBxQMHAIFEw0aFRsFFQEbBBsN
    [fingerprint_r3] => 
    [fingerprint_r4] => 
    [fingerprint_r5] => 
    [fingerprint_l1] => 
    [fingerprint_l2] => p/8BF2MAVQABLQCzAOMAAWMByAAlAQGCANEAowABWAGyAPcAAZ4AvgDaAAGpAHAAVgAB3ADLAAQBAo0APQDZAAHhALgAqwABrwDVAPoAAZMAogCcAAK6AGUA1wAB1gBRAI4AAdwAcwALAQLhAH8AeAAC0QDiAI8AAlIB6AC/AAJMASwAKwEB7QAvALUAAeEAMwB6AAHhACcALwEBMwD1ALsAAUwBfAAVEgYAAQUHChEWBAEDEAkDCQsHBAQFAgcKBBEDDRQPBgoFCBMIDAoBBwEWAwcFAgoPAAUJERADCxYQBRELDwkQDQ8CBBMNEQkODAEJBQMTFA0AFAAKERYJBRYNBgERDBMLEA4EBQsCAQoWFAYBAwELDggHEQ4BDA0CBRQPCQ8ECQEWCA0EERIOEQsBDAsNBAwFEBIIBxYVDgoJDAsLBgoDDgcWCxUIBQwCDgMPDAkLAAEQCBQMDw4KEw8SDBAPDBQCERUMEwAOEwkGAhYTBgsUCA8BCBITEwsOCwkAFRMDBhAGAQ0MABAAEgQQDRUEEgESAgIIFQEVAg==
    [fingerprint_l3] => 
    [fingerprint_l4] => 
    [fingerprint_l5] => 
    [gender] => 1
    [sitecode] => V02-04
    [member_fp_name] => 
    [member_fp_value] => 
)

INFO  - 2017-01-19 05:36:09 --> Create Visit
INFO  - 2017-01-19 05:36:09 --> Array
(
    [patientid] => KH002100003319
    [age] => 33
    [serviceid] => 1
    [visitdate] => 2014/06/30
    [externalcode] => 33333
    [externalcode2] => 
    [refer_to_vcct] => 0
    [refer_to_oiart] => 1
    [refer_to_std] => 0
    [info] => Positive
    [sitecode] => V02-04
    [member_fp_name] => 
    [member_fp_value] => 
)

INFO  - 2017-01-19 09:30:14 --> Patient searching
INFO  - 2017-01-19 09:30:14 --> Array
(
    [fingerprint_r1] => 
    [fingerprint_r2] => p/8BHbYApQABggCtANUAASsBmgCzAAEwAcAAbAACOwGmAMQAAXwAewCzAAF3AEoAuwABWgCHAOUAAXEAVgC5AAFgAIkAWQABkwBpANIAAWsAdAB8AAGYAJcA7wABJQFwAOwAAR8BeABJAAFSAY4ANQABmABMAH4AAR0AqADdAAF3AIIANgEBKwG8ACsBATABUABdAAEGAFwACwEBHwFnAKYAAXcAXQCgAAJaAPYANgEBFwA6ALkAAlUAPgAaAQEfAdsAJQEBhwAcAKEAAfgAqgARAQYIFhcGGQEEDAcEAgkOBRYNBxEECBYMEQgXDQoZCA4PAgAKCAIFExsYGwYXEBQMARoVBxEEAAcKBRcJDwoFBhYIBRUNFxAZHAECCgYMDRALCwkHARkXFwsWCxECChYHBBQOBAUMBBYQCxQZFgEABgULDgoXBwUCFgoZBhwHAgwKBQsSFRUHDQgUCRUKAwkNEQ0FCgIAAxEAGBMcEBITAQUMAggQBhAFABEFGRANBggcCgQZBQ0BHBcVDAcIAgsaDRcUCAsQDhMMEAkDDxIaFA8SDBYcCw8SDRYUCwMACxYABwADDgIDEgcTERUGFQgZCxYJGgoXCRwUGwwTARMHAAkECxsRFRkaBwocFw4SGxsBBAMcCxYOGRQaBhoZEhEQDwUDGgwTDRMVGwcVFwcLGwQYEhcPGBEYDAAPGAEaHBsAEwAYBxgEEhkaEBgAGwMYAxgL
    [fingerprint_r3] => 
    [fingerprint_r4] => 
    [fingerprint_r5] => 
    [fingerprint_l1] => 
    [fingerprint_l2] => p/8BHlMApwABTwBMAJkAAUoAaADoAAFPAKoAlQABawCQAJAAAWYAaAA/AAGpADsApQABRABcALIAAU8AfAC5AAFaAE0AyQAB/gBqAJsAAVoAIwDHAAFEACYA9wAB8gCaANkAAVoAdgBxAAF3AFoA7QABAwFHAFMAAboAJADSAAH4AJkAqgABYABeAAgBAfgAYQBzAAF3AD8A4AABRABPAPQAAUoAXQBRAAFYAUEAlgAB+AA8AIgAAT4AkQA2AQHyACYADwEB7QBFAIEAAT4AVABhAAGYAKcAEQsZHAEYFg8HABgZDwIAAQYYHRcdEBQOGBwXBQYBEBcUHQEZAAYbDBMWARwAGAMEFhUAChIDCQcHChMPFQkSBBYCBhkVEQ8VBwEKARwUCBIIBxMCDBUUFwkACAocHQcGDBEGHA4dFQsPCQAZBxgdBRAFCgQAHAQOCQYUEA4XDBYKGAIJChQJCwIVCwYRCQEUGRQWCQoODQgKHAgAHBAIBBkdDRIYFAkBBgoMCxsWEgoJCAoZEQYCCBMVAg0OBRQFHA4bFQcZDA8JChwXGRAWEQQUAgcbEw4QGB0BHQsYCAMBDgsAEwwPBw8RDAkbEQsHGw8HEg8IBwQDDgoDGRcABBMJGBAPDRIOCRkLGRoTEgANAwgOGwsNBw0EARcKFxwFEw0bAgscAhINCQMUBwMGEBkFGgIEBRoPGhYaDQMXAwUaGxoVCxAaDBMDGhIaAw==
    [fingerprint_l3] => 
    [fingerprint_l4] => 
    [fingerprint_l5] => 
    [gender] => 1
    [sitecode] => V02-04
    [member_fp_name] => 
    [member_fp_value] => 
)

ERROR - 2017-01-19 09:30:14 --> SDK is busy with other service
INFO  - 2017-01-19 09:30:52 --> Patient searching
INFO  - 2017-01-19 09:30:52 --> Array
(
    [fingerprint_r1] => 
    [fingerprint_r2] => p/8BHjwAsgABIgCMAKAAAY0AngD8AAE7ASMAzgACOQCSAJIAAkcBlwDlAAErAVAAOwACAACUAC8AAkcBZQB3AAGvAJ0A1wACfADCAE4AAkcBqAAPAQFBAVoAdgABAADIAM4AAjABoQA9AAGTAKQAHQEBUgGLAHoAAUwBugC2AAKCAL0ALwECWAFSACgBAVIBxAA6AAFBAcUAhAABjQCPAPwAAkcBhADwAAJMAYIA6QACQQFGAMwAAuEAxQAVAQFBATQADAEBdwDMACYBAkwBIgAsAQEwAbEAFxgIDBYCAQQPCwUJFhcSHBwaDgcKFAsCGAUXBRYYFgUCBQQQEhoZAA0RAhcaCxIPCxYYCQ8aAhgPAgMZFwkOFAoOAgkdGwEQAwAQCBILDxYWCRwPExscCwkRCQ0LBRoCCxcdExAMFAcRAREVBAgEFQsYBQ0VChEECgcPFwsJDwUBCAkBBREVEAwGEgIaFg8YAg0cAgQMCAYbAwEVEA4BDBsZGgUYGQAMEhYGBwkEEAoFARoNCw0ACBcZFg0VFBwWDRUYARoJAhETFhMXDQEYERAHERATGBUODQQOBgABCA4ZAQQKEgUTDxwFEhcFGRsYGxcQBggHBA4QFBYZHA0TAhkMCRkYABsAEwsZCAwODAcABBsWHQMTBRUIAQoSDRUHBAcYAwQUCAoTAxcDHRkDDBsFEhMEBggUHRcDAQYUCgYTGh0YHRYABhEUHQANCh0PGwESGxkGDRQDBhIdHBUaFBwU
    [fingerprint_r3] => 
    [fingerprint_r4] => 
    [fingerprint_r5] => 
    [fingerprint_l1] => 
    [fingerprint_l2] => p/8BHqMAKgEC4QB7ADUBAeEAyAAqAQHhAHgAnwAB1gDpAO0AAYcAYgBSAAHhAHgArgABKACVAB8BAecA5ADHAAKTAMcAqAABYwFHAMYAAjkAygBxAAG0ALIAYAABugCOAD0AAtYAUQCfAAHnAFUA8wAB8gDTAJ8AAakAyAC+AAKpAIoA1AAC4QBdAOQAATkAfgAaAAHcAHIAGAABLQDUABYBAk8AXAA2AQHnAN8A+wACdwDAAPkAAlIBxwAIAQIzAOIAZgABYwG/AAcBAncAPgBFAAHhAKAAGhwUFRwZCRAGAxgEGhkPEwAHFhoRCQIWCxsWHBoYFhgLDAgRGBkXAREQAQccGAIaFhkCHBMKAgANFAQIBR0OAwoOAQASBggJBg4aBAgQGQQAHA0VFgQPChALBxwTEhsMBQ0cBAIZDA0AGhgIAgcCGAAWCQsHGgoGEgMHGQAZBBEQGxkREwYFFQ8SFwcZCAoDBRQHFhgRGRISERcPEgoCBB0VEw4aCBAMCRsXABwRHAgcEhMDCQwSCQcSAQ8PBgQJEQsdFAECEg4HDwsNDgUGCQkDHQ0DBQQQGQkMBQcTEQYBHBcTDw4BEwMMDBQBGggLEhASCBEbGRAOHRsNAwsGBQAPDBUGDAgbAw0ZEwMdFxIXAhccBxEXCgsUDgwHBgkOBwoKBQwdBh0DGxMJAQoLFRsUCh0DFAkFBBsDFRsVGRs=
    [fingerprint_l3] => 
    [fingerprint_l4] => 
    [fingerprint_l5] => 
    [gender] => 1
    [sitecode] => V02-04
    [member_fp_name] => 
    [member_fp_value] => 
)

ERROR - 2017-01-19 09:30:52 --> SDK is busy with other service
INFO  - 2017-01-19 10:08:18 --> Patient searching
INFO  - 2017-01-19 10:08:18 --> Array
(
    [fingerprint_r1] => 
    [fingerprint_r2] => p/8BHtkArQABMAHkAMAAAXcAhQCzAAFVAJIAswABYAC0AOAAAWYApADLAAFmAHgAsAABVQCpAOUAARoBvADUAAFrALgA9AABHwHvAN4AASUB0ADqAAEfAYsAdwABHQDiANkAAWsAUAC1AAFEALIAdAABngCPAFcAAQwAZgDVAAFaAJIAAgEBGgF0AN4AAWAAyQBRAAGYAE0A1AACTwBRABcBARQBXgAKAQFgAL8AKQEBNgF1AA8BARoBugBCAAFYAdAALgABmAC3AKkAAXEApgCgAAFmAKcABwQCBgMCBAgKDRMRFhccHQkECQcUGgEAGRcNAREVCw0HCAkLAwYHBQQFCAUDHQsECwgaGwUDFQ4JCBkSCgEMEAsKABwUGxIHFhkCHQ0IAxwRDgwPBQILBwUcEgkTFQ4GEQYPFAgcBR0NAAgBDxARAhMGEwIdDwkFCwESEwQNEBoSBBkTHQwIABcTBh0JDQ8aAhwBHBMDEwUKCAUGFxIcDwcTAB0IAxgJDgIXEQoACwUEHAcDEw4RAxUGFxUQFAQBEgUHDQQKCQoDDBgSBgwCDBkRBQALAAQTBQEVAhgLEgsOAxkHFhMcDBYVFhIWEQAPBwoZFRgHAw8JEwwaGQkMFBgEDxsQGwIPHRAYGRcHGAgdFBcODgwYDRgKHBQcEAEPBhAAFB0aCA8WDgwbEQwWBxgXHBoTDAAaGBYOEAEUHRscGwAbCBQKFAEbDRsKGw==
    [fingerprint_r3] => 
    [fingerprint_r4] => 
    [fingerprint_r5] => 
    [fingerprint_l1] => 
    [fingerprint_l2] => p/8BJWUArAABTwB3AMAAAVUAgQCmAAFgAFYAuAABSgCuAJIAASUBbgC1AAFVAKMAkQABcQC8AI4AAXcAQADaAAFEAKcAggABfABvAEsAAa8AhwDwAAFVAEEA6AAB/gBHAAsBAf4AlgDBAAFaAK8AqQABawCBAEIAAZ4AtgDXAAFgAGgA1gACAwFTAGcAAcUAhgB6AAGCAF4A7wABSgCfADUAAZ4AZwBfAAFdAXoA9gABCQFvAAIBAU8AuAA3AQHyADcAGwEBRACAABABAQMBJQAUAQH4AKoACQEBVQBLACABAfgAzwAtAQL+AFMAngABRAB0AIMAAXwAUgCSAAE+AGQAcQABpADTAAQGISMFAAEFDAgYCwQHBgkZGAQJJBcbHQMAJBMiFAoQHw0fGxMXFwocGQ8EACEbDSIkBQIDBQcJGRUGBxogAyEcGA8GAQAVEhIBAQIYFQACGQsVDA8HDgEAIxwLEBYOAgEDCRQSBQUhFCQODxIDHQ0NDA0VFQgYEiMiAiIGFAMjIyQiFxcQEQ4LEgIGHx0kCggDCBITCg8JFBcLFQ0ZDgUSAAwSIxMcHiEiHgsiEwAiAhQFIxkSDwIfGREPBBQCIQMCHBUhJBoeAgQGIgsODQgBIQ4GEg4iCQIjCwEeESAeDAMeGB0MFAoCCRsMCxEOBB8VChYZDBICGAEUEyQQIxcNGB8cIRMVAyIKFBAcDR8MIxQHFB4ZACQIAAgFGxUTEAQiAiQAFBIhAQ8IARsZDxQIIR8YHBIOBx0ICwUCBxgIDgkhFxsIIhARAR0VGhwYEREEFxYRAgciFBYRBwsCGxwIIwkQHg4dGSMKCRYcEQsPJBYgHBoLIhYdGBoYIBEaGRMWBhYHFiALBBYaER8eIBggGRofCCQIEyAOHgcMEyAPHSMgBx0T
    [fingerprint_l3] => 
    [fingerprint_l4] => 
    [fingerprint_l5] => 
    [gender] => 1
    [sitecode] => V02-04
    [member_fp_name] => 
    [member_fp_value] => 
)

ERROR - 2017-01-19 10:08:18 --> SDK is busy with other service
INFO  - 2017-01-19 10:08:27 --> Patient registration
INFO  - 2017-01-19 10:08:27 --> Array
(
    [fingerprint_r1] => 
    [fingerprint_r2] => p/8BHtkArQABMAHkAMAAAXcAhQCzAAFVAJIAswABYAC0AOAAAWYApADLAAFmAHgAsAABVQCpAOUAARoBvADUAAFrALgA9AABHwHvAN4AASUB0ADqAAEfAYsAdwABHQDiANkAAWsAUAC1AAFEALIAdAABngCPAFcAAQwAZgDVAAFaAJIAAgEBGgF0AN4AAWAAyQBRAAGYAE0A1AACTwBRABcBARQBXgAKAQFgAL8AKQEBNgF1AA8BARoBugBCAAFYAdAALgABmAC3AKkAAXEApgCgAAFmAKcABwQCBgMCBAgKDRMRFhccHQkECQcUGgEAGRcNAREVCw0HCAkLAwYHBQQFCAUDHQsECwgaGwUDFQ4JCBkSCgEMEAsKABwUGxIHFhkCHQ0IAxwRDgwPBQILBwUcEgkTFQ4GEQYPFAgcBR0NAAgBDxARAhMGEwIdDwkFCwESEwQNEBoSBBkTHQwIABcTBh0JDQ8aAhwBHBMDEwUKCAUGFxIcDwcTAB0IAxgJDgIXEQoACwUEHAcDEw4RAxUGFxUQFAQBEgUHDQQKCQoDDBgSBgwCDBkRBQALAAQTBQEVAhgLEgsOAxkHFhMcDBYVFhIWEQAPBwoZFRgHAw8JEwwaGQkMFBgEDxsQGwIPHRAYGRcHGAgdFBcODgwYDRgKHBQcEAEPBhAAFB0aCA8WDgwbEQwWBxgXHBoTDAAaGBYOEAEUHRscGwAbCBQKFAEbDRsKGw==
    [fingerprint_r3] => 
    [fingerprint_r4] => 
    [fingerprint_r5] => 
    [fingerprint_l1] => 
    [fingerprint_l2] => p/8BJWUArAABTwB3AMAAAVUAgQCmAAFgAFYAuAABSgCuAJIAASUBbgC1AAFVAKMAkQABcQC8AI4AAXcAQADaAAFEAKcAggABfABvAEsAAa8AhwDwAAFVAEEA6AAB/gBHAAsBAf4AlgDBAAFaAK8AqQABawCBAEIAAZ4AtgDXAAFgAGgA1gACAwFTAGcAAcUAhgB6AAGCAF4A7wABSgCfADUAAZ4AZwBfAAFdAXoA9gABCQFvAAIBAU8AuAA3AQHyADcAGwEBRACAABABAQMBJQAUAQH4AKoACQEBVQBLACABAfgAzwAtAQL+AFMAngABRAB0AIMAAXwAUgCSAAE+AGQAcQABpADTAAQGISMFAAEFDAgYCwQHBgkZGAQJJBcbHQMAJBMiFAoQHw0fGxMXFwocGQ8EACEbDSIkBQIDBQcJGRUGBxogAyEcGA8GAQAVEhIBAQIYFQACGQsVDA8HDgEAIxwLEBYOAgEDCRQSBQUhFCQODxIDHQ0NDA0VFQgYEiMiAiIGFAMjIyQiFxcQEQ4LEgIGHx0kCggDCBITCg8JFBcLFQ0ZDgUSAAwSIxMcHiEiHgsiEwAiAhQFIxkSDwIfGREPBBQCIQMCHBUhJBoeAgQGIgsODQgBIQ4GEg4iCQIjCwEeESAeDAMeGB0MFAoCCRsMCxEOBB8VChYZDBICGAEUEyQQIxcNGB8cIRMVAyIKFBAcDR8MIxQHFB4ZACQIAAgFGxUTEAQiAiQAFBIhAQ8IARsZDxQIIR8YHBIOBx0ICwUCBxgIDgkhFxsIIhARAR0VGhwYEREEFxYRAgciFBYRBwsCGxwIIwkQHg4dGSMKCRYcEQsPJBYgHBoLIhYdGBoYIBEaGRMWBhYHFiALBBYaER8eIBggGRofCCQIEyAOHgcMEyAPHSMgBx0T
    [fingerprint_l3] => 
    [fingerprint_l4] => 
    [fingerprint_l5] => 
    [gender] => 1
    [sitecode] => V02-04
    [member_fp_name] => 
    [member_fp_value] => 
)

INFO  - 2017-01-19 10:53:19 --> Synchronization Update
INFO  - 2017-01-19 10:53:19 --> Array
(
    [patient] => {"patientid":"52342e8d-f8c7-4c95-bc58-b6019b446285","fingerprint_r1":"","fingerprint_r2":"p/8BHtkArQABMAHkAMAAAXcAhQCzAAFVAJIAswABYAC0AOAAAWYApADLAAFmAHgAsAABVQCpAOUAARoBvADUAAFrALgA9AABHwHvAN4AASUB0ADqAAEfAYsAdwABHQDiANkAAWsAUAC1AAFEALIAdAABngCPAFcAAQwAZgDVAAFaAJIAAgEBGgF0AN4AAWAAyQBRAAGYAE0A1AACTwBRABcBARQBXgAKAQFgAL8AKQEBNgF1AA8BARoBugBCAAFYAdAALgABmAC3AKkAAXEApgCgAAFmAKcABwQCBgMCBAgKDRMRFhccHQkECQcUGgEAGRcNAREVCw0HCAkLAwYHBQQFCAUDHQsECwgaGwUDFQ4JCBkSCgEMEAsKABwUGxIHFhkCHQ0IAxwRDgwPBQILBwUcEgkTFQ4GEQYPFAgcBR0NAAgBDxARAhMGEwIdDwkFCwESEwQNEBoSBBkTHQwIABcTBh0JDQ8aAhwBHBMDEwUKCAUGFxIcDwcTAB0IAxgJDgIXEQoACwUEHAcDEw4RAxUGFxUQFAQBEgUHDQQKCQoDDBgSBgwCDBkRBQALAAQTBQEVAhgLEgsOAxkHFhMcDBYVFhIWEQAPBwoZFRgHAw8JEwwaGQkMFBgEDxsQGwIPHRAYGRcHGAgdFBcODgwYDRgKHBQcEAEPBhAAFB0aCA8WDgwbEQwWBxgXHBoTDAAaGBYOEAEUHRscGwAbCBQKFAEbDRsKGw==","fingerprint_r3":"","fingerprint_r4":"","fingerprint_r5":"","fingerprint_l1":"","fingerprint_l2":"p/8BJWUArAABTwB3AMAAAVUAgQCmAAFgAFYAuAABSgCuAJIAASUBbgC1AAFVAKMAkQABcQC8AI4AAXcAQADaAAFEAKcAggABfABvAEsAAa8AhwDwAAFVAEEA6AAB/gBHAAsBAf4AlgDBAAFaAK8AqQABawCBAEIAAZ4AtgDXAAFgAGgA1gACAwFTAGcAAcUAhgB6AAGCAF4A7wABSgCfADUAAZ4AZwBfAAFdAXoA9gABCQFvAAIBAU8AuAA3AQHyADcAGwEBRACAABABAQMBJQAUAQH4AKoACQEBVQBLACABAfgAzwAtAQL+AFMAngABRAB0AIMAAXwAUgCSAAE+AGQAcQABpADTAAQGISMFAAEFDAgYCwQHBgkZGAQJJBcbHQMAJBMiFAoQHw0fGxMXFwocGQ8EACEbDSIkBQIDBQcJGRUGBxogAyEcGA8GAQAVEhIBAQIYFQACGQsVDA8HDgEAIxwLEBYOAgEDCRQSBQUhFCQODxIDHQ0NDA0VFQgYEiMiAiIGFAMjIyQiFxcQEQ4LEgIGHx0kCggDCBITCg8JFBcLFQ0ZDgUSAAwSIxMcHiEiHgsiEwAiAhQFIxkSDwIfGREPBBQCIQMCHBUhJBoeAgQGIgsODQgBIQ4GEg4iCQIjCwEeESAeDAMeGB0MFAoCCRsMCxEOBB8VChYZDBICGAEUEyQQIxcNGB8cIRMVAyIKFBAcDR8MIxQHFB4ZACQIAAgFGxUTEAQiAiQAFBIhAQ8IARsZDxQIIR8YHBIOBx0ICwUCBxgIDgkhFxsIIhARAR0VGhwYEREEFxYRAgciFBYRBwsCGxwIIwkQHg4dGSMKCRYcEQsPJBYgHBoLIhYdGBoYIBEaGRMWBhYHFiALBBYaER8eIBggGRofCCQIEyAOHgcMEyAPHSMgBx0T","fingerprint_l3":"","fingerprint_l4":"","fingerprint_l5":"","gender":1,"age":null,"sitecode":"","datebirth":"","createdate":"2017-01-19 16:08:32","updatedate":"2017-01-19 16:08:32","visits":[]}
    [patientid] => KH002100003301
    [sitecode] => V02-04
    [member_fp_name] => 
    [member_fp_value] => 
)

