ALTER TABLE `mpi_patient` ADD `id` INT(11) NOT NULL FIRST;
ALTER TABLE `mpi_update`.`mpi_patient`
CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '' ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`id`)  COMMENT '',
ADD UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '';
